### ISSUE TITLE
Trigger automation on new task, actions on tasks

### ISSUE THREAD

**Issue by otmezger** [nitobuendia/asana-custom-component#3]
Hi, I was wondering if this plug-in can trigger automations based on tasks. For instance a new task created on a project. 

I also wanted to know if it would be possible to act on those tasks and edit them. Specifically I’m looking to create an automation that picks up all new tasks created on specific projects and add them to a secondary project. The tasks will have 2 projects in the end. 

Do you think this can be done here, or could be done by changing the code?

**Comment by nitobuendia** [comment]
Hi @otmezger  - thanks for reaching out and asking.

With the current design, this is only meant to be a sensor. As such, you can only monitor the number of tasks and the actual tasks.

Natively, there will be no triggers when new tasks are created. You could potentially create a sensor off the `counter_future_all` attribute and do an action if that number varies. Although that won't capture if you deleted and added one task. You could also potentially create a templated sensor from `list_future_7days` or alike, and see if the values changed. You may need to sort and join, but it should detect any changes. For ideas on how to do this, you could [ask on the Community](https://community.home-assistant.io/) and see if someone can help.

Alternatively, [using Node-RED](https://community.home-assistant.io/t/home-assistant-community-add-on-node-red/55023), you could parse this data through a JavaScript function and do advanced logic like this.

This is also not an integration designed to make changes on your projects, it only performs reads form the API. Perhaps something like [Zapier](https://zapier.com/apps/asana/integrations) might be a better fit for you. Asana also has [these features](https://asana.com/product/automation) for paid users.

As for whether this code could support it, I don't think it's the direction the project is going. This is designed to read data from the API, not write to it and it's designed to be a sensor not something that would be triggering advanced.

I hope the ideas shared above may lead you to find a solution to your problem.
